# ClouDNS DDNS Docker Compose for washyushomelab.ip-ddns.com
version: '3.8'

services:
  cloudns-updater:
    image: alpine:latest
    container_name: cloudns-updater
    environment:
      # Update interval in seconds (300 = 5 minutes)
      - UPDATE_INTERVAL=300
    volumes:
      - ./cloudns-logs:/var/log
    command: |
      sh -c '
      apk add --no-cache curl
      
      UPDATE_URL="https://ipv4.cloudns.net/api/dynamicURL/?q=OTQ2OTU4OTo2MDQwMjcyOTk6ODZhN2RhNmYzNTQ1NDIwMzY0ZTA0NzMzYjVkZWFkMThkNTNhNzUwMmQ5NzZjNTg4YWJkY2E4NDQzZDhiMDc1Ng"
      
      while true; do
        echo "$$(date): Updating IP..." >> /var/log/cloudns-update.log
        RESPONSE=$$(curl -s "$$UPDATE_URL")
        echo "$$(date): Response=$$RESPONSE" >> /var/log/cloudns-update.log
        
        sleep $$UPDATE_INTERVAL
      done
      '
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "pgrep", "sleep"]
      interval: 5m
      timeout: 10s
      retries: 3