---
- name: Deploy Simple Mail Server (Maddy)
  hosts: homelab2
  become: yes
  vars:
    mail_domain: shaunjackson.space
    mail_hostname: mail.shaunjackson.space
    mail_dir: /opt/maddy
    admin_password: "{{ vault_mail_admin_password | default('ChangeMailPass123!') }}"
    
  tasks:
    - name: Create mail directory
      file:
        path: "{{ mail_dir }}"
        state: directory
        mode: '0755'

    - name: Create Maddy configuration
      copy:
        content: |
          # Maddy Mail Server Configuration
          
          # Domain configuration
          $(hostname) = {{ mail_hostname }}
          $(primary_domain) = {{ mail_domain }}
          $(local_domains) = $(primary_domain)
          
          # TLS configuration (will use NPM certs)
          tls off
          
          # Storage & state directory
          state_dir /data
          runtime_dir /tmp/maddy-runtime
          
          # Log configuration
          log stderr
          
          # Authentication
          auth.pass_table local_authdb {
              table sql_table {
                  driver sqlite3
                  dsn /data/credentials.db
                  table_name passwords
              }
          }
          
          # Storage configuration
          storage.imapsql local_mailboxes {
              driver sqlite3
              dsn /data/imapsql.db
          }
          
          # SMTP configuration
          smtp tcp://0.0.0.0:25 {
              hostname $(hostname)
              tls off
              
              source $(local_domains) {
                  reject_invalid_recipients
                  destination postmaster $(local_domains) {
                      deliver_to &local_mailboxes
                  }
                  destination $(local_domains) {
                      deliver_to &local_mailboxes
                  }
                  default_destination {
                      reject
                  }
              }
              default_source {
                  reject
              }
          }
          
          # Submission configuration
          submission tcp://0.0.0.0:587 {
              hostname $(hostname)
              tls off
              
              auth &local_authdb
              
              source $(local_domains) {
                  destination postmaster $(local_domains) {
                      deliver_to &local_mailboxes
                  }
                  destination $(local_domains) {
                      deliver_to &local_mailboxes
                  }
                  default_destination {
                      deliver_to &remote_queue
                  }
              }
              default_source {
                  reject
              }
          }
          
          # IMAP configuration  
          imap tcp://0.0.0.0:143 {
              hostname $(hostname)
              tls off
              
              auth &local_authdb
              storage &local_mailboxes
          }
          
          # Remote queue for sending mail
          target.queue remote_queue {
              target.smtp {
                  attempt_starttls yes
                  require_tls no
                  auth off
              }
          }
        dest: "{{ mail_dir }}/maddy.conf"

    - name: Deploy Maddy mail server
      docker_container:
        name: maddy-mail
        image: foxcpp/maddy:latest
        state: started
        restart_policy: unless-stopped
        volumes:
          - "{{ mail_dir }}/data:/data"
          - "{{ mail_dir }}/maddy.conf:/etc/maddy/maddy.conf:ro"
        ports:
          - "25:25"     # SMTP
          - "587:587"   # Submission
          - "143:143"   # IMAP
        env:
          MADDY_HOSTNAME: "{{ mail_hostname }}"
          MADDY_DOMAIN: "{{ mail_domain }}"

    - name: Wait for Maddy to start
      wait_for:
        port: 25
        host: localhost
        delay: 10
        timeout: 60

    - name: Create admin mailbox
      docker_exec:
        container: maddy-mail
        command: |
          maddy creds create admin@{{ mail_domain }} <<< '{{ admin_password }}'
          maddy imap-acct create admin@{{ mail_domain }}
      ignore_errors: yes

    - name: Create mail client guide
      copy:
        content: |
          # Mail Server Setup Guide
          
          ## Email Account Created
          - **Email**: admin@{{ mail_domain }}
          - **Password**: {{ admin_password }}
          
          ## DNS Records Required
          
          Add these to your DNS provider:
          
          ```
          Type  Name    Value                Priority
          A     mail    68.111.95.149        -
          MX    @       mail.{{ mail_domain }}  10
          TXT   @       "v=spf1 mx a ~all"   -
          ```
          
          ## Email Client Settings
          
          ### Incoming Mail (IMAP)
          - Server: mail.{{ mail_domain }}
          - Port: 143
          - Security: None (we'll use NPM for TLS)
          - Username: admin@{{ mail_domain }}
          - Password: {{ admin_password }}
          
          ### Outgoing Mail (SMTP)
          - Server: mail.{{ mail_domain }}
          - Port: 587
          - Security: None (we'll use NPM for TLS)
          - Username: admin@{{ mail_domain }}
          - Password: {{ admin_password }}
          
          ## Webmail Access
          
          For webmail, we'll add Roundcube:
          
          ```bash
          docker run -d \
            --name roundcube \
            --link maddy-mail:mail \
            -e ROUNDCUBEMAIL_DEFAULT_HOST=mail \
            -e ROUNDCUBEMAIL_SMTP_SERVER=mail \
            -e ROUNDCUBEMAIL_SMTP_PORT=587 \
            -p 8082:80 \
            roundcube/roundcubemail:latest
          ```
          
          Then access at: http://192.168.10.108:8082
          
          ## NPM Configuration
          
          Add proxy host:
          - Domain: mail.{{ mail_domain }}
          - Forward to: 192.168.10.108:8082 (for webmail)
          - Enable SSL
          
          ## Testing
          
          1. Send email to: admin@{{ mail_domain }}
          2. Send email from admin to external address
          3. Check spam score at mail-tester.com
          
          ## Important Notes
          
          - This is a basic mail server
          - For production use, consider:
            - DKIM signing
            - Better spam filtering
            - Backup MX records
            - Rate limiting
        dest: "{{ mail_dir }}/mail-client-setup.md"

    - name: Deploy Roundcube webmail
      docker_container:
        name: roundcube
        image: roundcube/roundcubemail:latest
        state: started
        restart_policy: unless-stopped
        links:
          - "maddy-mail:mail"
        ports:
          - "8082:80"
        env:
          ROUNDCUBEMAIL_DEFAULT_HOST: "mail"
          ROUNDCUBEMAIL_SMTP_SERVER: "mail"
          ROUNDCUBEMAIL_SMTP_PORT: "587"
          ROUNDCUBEMAIL_DEFAULT_PORT: "143"

    - name: Display mail server info
      debug:
        msg: |
          Simple mail server deployed!
          
          Email Account:
          - Address: admin@{{ mail_domain }}
          - Password: {{ admin_password }}
          
          Webmail Access: http://{{ ansible_default_ipv4.address }}:8082
          
          Required DNS Records:
          1. A record: mail → 68.111.95.149
          2. MX record: @ → mail.{{ mail_domain }}
          3. SPF record: "v=spf1 mx a ~all"
          
          Setup guide: {{ mail_dir }}/mail-client-setup.md