---
- name: Deploy Mailcow Mail Server
  hosts: homelab2
  become: yes
  vars:
    mailcow_dir: /opt/mailcow-dockerized
    mailcow_hostname: mail.shaunjackson.space
    mailcow_timezone: America/New_York
    admin_email: admin@shaunjackson.space
    
  tasks:
    - name: Install required packages
      apt:
        name:
          - git
          - curl
          - wget
        state: present

    - name: Clone Mailcow repository
      git:
        repo: https://github.com/mailcow/mailcow-dockerized
        dest: "{{ mailcow_dir }}"
        version: master

    - name: Generate Mailcow configuration
      shell: |
        cd {{ mailcow_dir }}
        ./generate_config.sh << EOF
        mail.shaunjackson.space
        {{ mailcow_timezone }}
        EOF
      args:
        creates: "{{ mailcow_dir }}/mailcow.conf"

    - name: Update Mailcow configuration
      lineinfile:
        path: "{{ mailcow_dir }}/mailcow.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^HTTP_PORT=', line: 'HTTP_PORT=8081' }
        - { regexp: '^HTTPS_PORT=', line: 'HTTPS_PORT=8444' }
        - { regexp: '^API_KEY=', line: 'API_KEY=mailcow-api-key-{{ ansible_date_time.epoch }}' }
        - { regexp: '^SKIP_LETS_ENCRYPT=', line: 'SKIP_LETS_ENCRYPT=y' }
        - { regexp: '^SKIP_CLAMD=', line: 'SKIP_CLAMD=n' }
        - { regexp: '^MAILCOW_HOSTNAME=', line: 'MAILCOW_HOSTNAME={{ mailcow_hostname }}' }

    - name: Pull Mailcow images
      shell: |
        cd {{ mailcow_dir }}
        docker-compose pull
      async: 600
      poll: 10

    - name: Start Mailcow
      shell: |
        cd {{ mailcow_dir }}
        docker-compose up -d
      async: 300
      poll: 10

    - name: Wait for Mailcow to be ready
      wait_for:
        port: 8081
        host: localhost
        delay: 30
        timeout: 180

    - name: Create DNS configuration guide
      copy:
        content: |
          # Mail Server DNS Configuration
          
          ## Required DNS Records for shaunjackson.space
          
          Add these records to your DNS provider:
          
          ### 1. Mail Server Records
          ```
          Type  Name    Value                   Priority
          A     mail    68.111.95.149           -
          MX    @       mail.shaunjackson.space 10
          ```
          
          ### 2. SPF Record (Prevent Spoofing)
          ```
          Type  Name    Value
          TXT   @       "v=spf1 mx a ip4:68.111.95.149 ~all"
          ```
          
          ### 3. DKIM Record (Will be generated after setup)
          ```
          Type  Name              Value
          TXT   dkim._domainkey   (Get from Mailcow Admin → Configuration → DKIM)
          ```
          
          ### 4. DMARC Record (Email Authentication)
          ```
          Type  Name     Value
          TXT   _dmarc   "v=DMARC1; p=quarantine; rua=mailto:admin@shaunjackson.space"
          ```
          
          ### 5. Autodiscover Records (Optional but recommended)
          ```
          Type  Name          Value
          CNAME autodiscover  mail.shaunjackson.space
          CNAME autoconfig    mail.shaunjackson.space
          ```
          
          ### 6. Reverse DNS (PTR Record)
          Contact your ISP to set PTR record for 68.111.95.149 → mail.shaunjackson.space
          
          ## Mailcow Access
          
          - **Admin Panel**: https://mail.shaunjackson.space (after NPM setup)
          - **Local Access**: http://192.168.10.108:8081
          - **Default Login**: admin / moohoo
          - **Webmail**: https://mail.shaunjackson.space/SOGo
          
          ## First Steps After DNS Setup
          
          1. Login to Mailcow admin panel
          2. Change admin password immediately
          3. Go to Configuration → Domains → Add domain: shaunjackson.space
          4. Go to Configuration → Mailboxes → Add mailbox
             - Username: admin
             - Domain: shaunjackson.space
             - Password: (set strong password)
             - Quota: 10GB
          5. Get DKIM key from Configuration → DKIM
          6. Add DKIM record to DNS
          
          ## Email Client Configuration
          
          ### IMAP (Incoming)
          - Server: mail.shaunjackson.space
          - Port: 993 (SSL/TLS)
          - Username: admin@shaunjackson.space
          
          ### SMTP (Outgoing)
          - Server: mail.shaunjackson.space
          - Port: 587 (STARTTLS)
          - Username: admin@shaunjackson.space
          
          ## Testing Your Email
          
          1. Send test email to yourself
          2. Check spam score at: mail-tester.com
          3. Verify DKIM/SPF at: mxtoolbox.com
          
          ## NPM Proxy Configuration
          
          Add these proxy hosts:
          
          1. **Mail Admin**
             - Domain: mail.shaunjackson.space
             - Forward to: 192.168.10.108:8081
             - Enable Websockets Support
          
          2. **Webmail**
             - Domain: webmail.shaunjackson.space
             - Forward to: 192.168.10.108:8081
             
          ## Important Ports
          
          Router port forwarding needed:
          - 25 (SMTP) → 192.168.10.108:25
          - 587 (Submission) → 192.168.10.108:587
          - 993 (IMAPS) → 192.168.10.108:993
          - 995 (POP3S) → 192.168.10.108:995
        dest: "{{ mailcow_dir }}/mail-setup-guide.md"

    - name: Display setup information
      debug:
        msg: |
          Mailcow is being deployed!
          
          This may take 5-10 minutes to fully start.
          
          Access at: http://{{ ansible_default_ipv4.address }}:8081
          Default login: admin / moohoo
          
          IMPORTANT: Complete DNS setup guide at:
          {{ mailcow_dir }}/mail-setup-guide.md
          
          Required DNS records:
          1. A record: mail.shaunjackson.space → {{ ansible_facts['default_ipv4']['address'] }}
          2. MX record: @ → mail.shaunjackson.space
          3. SPF, DKIM, DMARC records (see guide)
          
          Router ports to forward:
          - 25, 587, 993, 995 → 192.168.10.108