name: Test Suite

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run all tests
      run: npm test
    
    - name: Run unit tests only
      run: npm run test:unit
      continue-on-error: true
    
    - name: Run integration tests
      run: npm run test:integration
      continue-on-error: true
    
    - name: Run SSE-MCP integration test
      run: |
        # Start SSE server in background
        API_ACCESS_TOKEN=test-token-ci npm run start:sse &
        SSE_PID=$!
        # Wait for server to start
        sleep 5
        # Run integration test
        API_ACCESS_TOKEN=test-token-ci node tests/integration/sse-mcp-integration-runner.cjs
        # Kill SSE server
        kill $SSE_PID || true
      env:
        API_ACCESS_TOKEN: test-token-ci
    
    - name: Run tool tests
      run: npm run test:tools
      continue-on-error: true
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-${{ matrix.node-version }}
        path: coverage/
    
    - name: Check for stub implementations
      run: |
        echo "Checking for stub implementations..."
        grep -r "TODO\|placeholder\|stub" src/tools/ || true

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for console.log statements
      run: |
        if grep -r "console\.log" src/ --exclude-dir=node_modules; then
          echo "::warning::Found console.log statements in source code"
        fi